package com.fishercoder.solutions;

/**Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.*/
public class _389 {
	public char findTheDifference(String s, String t) {
		int ch = 0;
		char[] sa = s.toCharArray();
		char[] ta = t.toCharArray();
		for (int i = 0; i < sa.length; i++) {
			ch += ta[i] - sa[i];
		}
		return (char) (ch + ta[sa.length]);
	}
}
